---
# tasks file for blockscout

- name: Generate common-blockscout.env file file
  template:
    src: common-blockscout.env.j2
    dest: 'opstack-compose/blockscout/envs/common-blockscout.env'
    mode: '0644'

- name: Generate common-frontend.env file file
  template:
    src: common-frontend.env.j2
    dest: 'opstack-compose/blockscout/envs/common-frontend.env'
    mode: '0644'

- name: Start blockscout
  become: true
  community.docker.docker_compose_v2:
    project_src: 'opstack-compose/blockscout'
    #build: always
  timeout: 600
  retries: 5
  ignore_errors: yes

- name: Copy traefik dynamic config file
  template:
    src: traefik-dynamic-config.yml.j2
    dest: 'traefik/config/blockscout_config.yml'
    mode: '0644'
  when: explorer_domain != ""

- name: Restart docker compose
  become: true
  community.docker.docker_compose_v2:
    project_src: 'traefik'
    state: restarted
  timeout: 600
  retries: 5
  when: explorer_domain != ""

