
- name: Install hdwallet package
  community.general.pipx:
    name: hdwallet

- set_fact:
    have_all_private_keys: false
    have_no_private_keys: false

- set_fact:
    have_seed_phrase: true
  when: (seed_phrase is defined and seed_phrase != "" and seed_phrase != "test test test test test test test test test test test junk")

- set_fact:
    have_admin_key: true
  when: admin_private_key is defined and admin_private_key != ""

- set_fact:
    have_batcher_key: true
  when: batcher_private_key is defined and batcher_private_key != ""

- set_fact:
    have_proposer_key: true
  when: proposer_private_key is defined and proposer_private_key != ""

- set_fact:
    have_sequencer_key: true
  when: sequencer_private_key is defined and sequencer_private_key != ""

- set_fact:
    have_all_private_keys: true
  when: not have_seed_phrase and have_admin_key and have_batcher_key and have_proposer_key and have_sequencer_key

- set_fact:
    have_no_private_keys: true
  when: not have_admin_key and not have_batcher_key and not have_proposer_key and have_sequencer_key

- ansible.builtin.fail:
    msg: Either a seed phrase or all of the following private keys (Admin, Batcher, Proposer, and Sequencer) must be provided.
  when: not have_all_private_keys and not have_no_private_keys

- name: Generate data from existing mnemonic
  block:
  - name: Run generate_accounts using existng mnemonic
    script: 'generate_accounts.py mnemonic {{seed_phrase_language}} "{{seed_phrase}}"'
    args:
      executable: python3
    register: account_output
  - name: Read account variables
    set_fact:
      admin_private_key: '{{ (account_output.stdout | from_json).adminKey }}'
      batcher_private_key: '{{ (account_output.stdout | from_json).batcherKey }}'
      proposer_private_key: '{{ (account_output.stdout | from_json).proposerKey }}'
      sequencer_private_key: '{{ (account_output.stdout | from_json).sequencerKey }}'
  when: seed_phrase is defined and have_no_private_keys