---
# tasks file for opstack

#- name: Install required apt packages
#  become: true
#  apt:
#    name:
#      - software-properties-common
#      - git

- name: Install build-essential
  become: true
  apt: name=build-essential state=latest update_cache=yes

- name: Install requires package for apt module
  become: true
  apt:
    name:
      - software-properties-common
      - git
      - apache2-utils
      - global
      - python3-pip
      - python3-docker
 #     - python3-docker-compose
 #     - python
  register: task_result
  until: task_result is success
  retries: 3

#- name: Install Python Docker module
#  become: true
#  pip:
#    name: docker
#    extra_args: --force-reinstall

#- name: Install PyYaml
#  pip:
#    name: PyYAML==5.3.1

#- name: Install Python Docker compose module
#  become: true
#  pip:
#    name: docker-compose

#- name: Install Docker (including compose)
#  hosts: all
#  become: true

#  tasks:
- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install dependencies via apt
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg

- name: Add Docker's official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker's APT repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Docker
  become: true
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to Docker group
  become: true
  user:
    name: root # Please use another user, not root :-)
    append: yes
    groups: docker

#- name: Install ansible
#  include_role:
#    name: geerlingguy.ansible

#- name: Python setup
#  include_role:
#    name: geerlingguy.pip
#  vars:
#    ansible_become: true
#    pip_install_packages:
      #- name: flask
      #- name: waitress
      #- name: passlib
#      - name: docker
      #  version: 6.1.3
#      - name: docker-compose

- name: Clone opstack-compose repo
  git:
    repo: 'https://github.com/upnodedev/opstack-compose'
    dest: 'opstack-compose'

#- name: Docker setup
#  include_role:
#    name: geerlingguy.docker
#  vars:
#    ansible_become: true
#    docker_install_compose_plugin: true
#    docker_users:
 #     - '{{ansible_user}}'

- name: Copy traefik dynamic config file
  template:
    src: templ.env.j2
    dest: 'opstack-compose/.env'
    mode: '0644'

- name: Start opstack
  become: true
  community.docker.docker_compose_v2:
    project_src: 'opstack-compose'
    build: always
    profiles:
      - sequencer
    state: restarted
  timeout: 600
  retries: 5
  ignore_errors: yes

- name: Start blockscout
  become: true
  community.docker.docker_compose_v2:
    project_src: 'opstack-compose/blockscout'
    build: always
    profiles:
      - sequencer
    state: restarted
  timeout: 600
  retries: 5
  ignore_errors: yes
