---
# tasks file for opstack

- name: Clone opstack-compose repo
  git:
    repo: 'https://github.com/upnodedev/opstack-compose'
    dest: 'opstack-compose'

- name: Generate env file file
  template:
    src: opstack.env.j2
    dest: 'opstack-compose/.env'
    mode: '0644'

- name: Start opstack
  become: true
  community.docker.docker_compose_v2:
    project_src: 'opstack-compose'
    build: always
    profiles:
      - sequencer
  timeout: 600
  retries: 5
  ignore_errors: yes

#- name: Start blockscout
#  become: true
#  community.docker.docker_compose_v2:
#    project_src: 'opstack-compose/blockscout'
#    #build: always
#  timeout: 600
#  retries: 5
#  ignore_errors: yes

#- name: Generate faucet .env file file
#  template:
#    src: faucet.env.j2
#    dest: 'opstack-compose/faucet/.env'
#    mode: '0644'

#- name: Start faucet
#  become: true
#  community.docker.docker_compose_v2:
#    project_src: 'opstack-compose/faucet'
#  timeout: 600
#  retries: 5
#  ignore_errors: yes

#- name: Generate bridge indexer .env file file
#  template:
#    src: 'bridge-indexer.env.j2'
#    dest: 'opstack-compose/bridge/indexer.env'
#    mode: '0644'

#- name: Generate bridge ui.env file file
#  template:
#    src: 'bridge-ui.env.j2'
#    dest: 'opstack-compose/bridge/ui.env'
#    mode: '0644'

#- name: Start bridge
#  become: true
#  community.docker.docker_compose_v2:
#    project_src: 'opstack-compose/bridge'
#    #build: always
#  timeout: 600
#  retries: 5
#  ignore_errors: yes

- name: Copy traefik dynamic config file
  template:
    src: traefik-dynamic-config.yml.j2
    dest: 'traefik/config/opstack_config.yml'
    mode: '0644'

- name: Restart docker compose
  become: true
  community.docker.docker_compose_v2:
    project_src: 'traefik'
    state: restarted
  timeout: 600
  retries: 5

