---
# tasks file for bridge
- name: Read the deployment data
  shell: cat opstack-compose/data/deployments/artifact.json
  register: deploy_data_res

- name: Read the deployment data
  set_fact:
    deploy_data: "{{ deploy_data_res.stdout | from_json }}"

- name: extract DisputeGameFactoryProxy
  set_fact:
    dispute_gamefactory_proxy: '{{ deploy_data.DisputeGameFactoryProxy }}'

- name: extract L1StandardBridgeProxy
  set_fact:
    l1_standard_bridge_proxy: '{{ deploy_data.L1StandardBridgeProxy }}'

- name: Extract L2OutputOracleProxy
  set_fact:
    l2_output_oracle_proxy: '{{ deploy_data.L2OutputOracleProxy }}'

- name: extract OptimismPortalProxy
  set_fact:
    optimism_portal_proxy: '{{ deploy_data.OptimismPortalProxy }}'

- name: Generate bridge indexer .env file file
  template:
    src: 'bridge-indexer.env.j2'
    dest: 'opstack-compose/bridge/indexer.env'
    mode: '0644'

- name: Generate bridge ui.env file file
  template:
    src: 'bridge-ui.env.j2'
    dest: 'opstack-compose/bridge/ui.env'
    mode: '0644'

- name: Start bridge
  become: true
  community.docker.docker_compose_v2:
    project_src: 'opstack-compose/bridge'
    #build: always
  timeout: 600
  retries: 5
  ignore_errors: yes

- name: Copy traefik dynamic config file
  template:
    src: traefik-dynamic-config.yml.j2
    dest: 'traefik/config/bridge_config.yml'
    mode: '0644'
  when: bridge_indexer_domain != "" or bridge_ui_domain != ""

- name: Restart docker compose
  become: true
  community.docker.docker_compose_v2:
    project_src: 'traefik'
    state: restarted
  timeout: 600
  retries: 5