---
# tasks file for install-prerequisites
- name: Install build-essential
  become: true
  apt: name=build-essential state=latest update_cache=yes

- name: Install requires package for apt module
  become: true
  apt:
    name:
      - software-properties-common
      - git
      - apache2-utils
      - global
      - python3-pip
      - python3-docker
  register: task_result
  until: task_result is success
  retries: 3

#  tasks:
- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install dependencies via apt
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg

- name: Add Docker's official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker's APT repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Docker
  become: true
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to Docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: Start docker
  service: name=docker state=started
