---
# tasks file for traefik
- name: Create folder for traefik
  become: true
  become_user: '{{ansible_user}}'
  file:
    path: '{{user_dir}}/traefik'
    state: directory
    mode: '0755'

- name: Copy docker compose file
  template:
    src: docker-compose.yml.j2
    dest: '{{user_dir}}/traefik/docker-compose.yml'
    mode: '0644'

- name: Create config folder for traefik
  become: true
  become_user: '{{ansible_user}}'
  file:
    path: '{{user_dir}}/traefik/config'
    state: directory
    mode: '0755'

- name: Copy traefik dynamic config file
  template:
    src: dynamic_config.yml.j2
    dest: '{{user_dir}}/traefik/config/base_config.yml'
    mode: '0644'

- name: Create traefik_proxy network
  docker_network:
    name: traefik_proxy

- name: Restart docker compose
  become: true
  docker_compose:
    project_src: '{{user_dir}}/traefik'
    restarted: yes
  timeout: 600
  retries: 5
  register: traefik_restart_status
  ignore_errors: yes
